server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway

# 下面的方法写死了
#zuul:
#  routes:
#    myservice: # 这里是路由id，随意写
#      path: /user-service/** # 这里是映射路径
#      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址
#    myconsumer:
#      path: /consumer-demo/**
#      url: http://127.0.0.1:8080

# 第一版
#zuul:
#  routes:
#    myservice:
#      path: /user-service/**
#      serviceId: user-service-good-4 # 这样就没有把Id写死,这样还可以实现负载均衡以及请求转发

# 第二版: 上面版本的简化版本 (最好配置)
zuul:
  routes:
    consumer-demo-good-4: /consumer-demo/**
  ignored-services:  # 把所有想要暴露给外界的微服务写在这里
    - user-service-good-4

# 可以解决第一次会报错的问题，第二次刷新就没问题了
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

# 第三版: 什么都不用配置，默认去eureka去拉去所有的微服务，然后配置成 (访问的时候用默认id(user-service-good-4))
# 我们这里就不用默认配置了，因为名称很长